---
- name: Install pre-requisites
  ansible.builtin.apt:
    pkg:
      - apt-transport-https
      - software-properties-common
    state: latest  # noqa package-latest

- name: Grafana gpg key
  ansible.builtin.apt_key:
    url: https://packages.grafana.com/gpg.key
    id: "{{ grafana_key_id }}"
    state: present

- name: Add grafana repository
  ansible.builtin.apt_repository:
    repo: deb https://packages.grafana.com/oss/deb stable main

- name: Install grafana
  ansible.builtin.apt:
    pkg:
      - grafana
    state: latest  # noqa package-latest

- name: Copy specific config file if exists
  ansible.builtin.template:
    src: "{{ playbook_dir }}/templates/grafana.ini.j2"
    dest: /etc/grafana/
    owner: root
    group: grafana
    mode: '0640'
  notify:
    - Restart grafana
  ignore_errors: true  # noqa package-latest

- name: Enable grafana service
  ansible.builtin.systemd:
    name: grafana-server
    state: started
    enabled: true
